### ISSUE TITLE
uni.setTabBarItem(OBJECT)  文档错误

### ISSUE THREAD

**Issue by Ryokutouto** [dcloudio/unidocs-zh#5]
![image](https://user-images.githubusercontent.com/44834187/188041583-faf40c60-a9cc-4b38-b6a6-d15f6defb78a.png)
![image](https://user-images.githubusercontent.com/44834187/188041612-4a4e71ae-6759-4723-b173-47d32b4f2ef8.png)

**Comment by codexu** [comment]
感谢指出文档问题，另外支付宝小程序也支持网络图片。
我们尽快更新文档。
