### ISSUE TITLE
希望在文档中增加 vitest 的说明

### ISSUE THREAD

**Issue by ModyQyW** [dcloudio/unidocs-zh#9]
`vitest` 是 `vue` 目前推荐的测试工具，见 <https://cn.vuejs.org/guide/scaling-up/testing.html#unit-testing>。希望在文档中增加 `vitest` 的配置和使用说明。

**Comment by ModyQyW** [comment]
@StrivingRabbit 请问 https://github.com/dcloudio/unidocs-zh/commit/b5d271d03e32328a86623814f08f764ff3554424 和这个 issue 有什么关联的地方吗？

**Comment by Otto-J** [comment]
捞一下，感谢反馈。
vitest 配合 vite+vue3 是一个好的选择，有兴趣的话，你可以尝试调整，在 `preset vue3` 项目中进行处理。

时间比较久了，现在接入应该更容易了。
